---
- hosts: OBBservers
  remote_user: ansible
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: "Searching for a Stringi TMOUT"
      become: yes
      become_user: root
      tags: bashrc
      lineinfile:
          path: /etc/bashrc
          line: "export TMOUT=1800"
          state: present
      check_mode: yes
      register: presence
    - name: add TMOUT in bashrc file if its not preset
      shell: echo export TMOUT=1800 >> /etc/bashrc
      when: presence is changed
    - name: "Searching for a String"
      become: yes
      become_user: root
      tags: bashrc
      lineinfile:
          path: /etc/pam.d/passwd
          line: "password required pam_pwquality.so retry=3"
          state: present
      check_mode: yes
      register: presence
    - name: add pam_pwquality in file if its not preset
      shell: echo  password required pam_pwquality.so retry=3 >> /etc/pam.d/passwd
      when: presence is changed

    - name: Transfer script to remote location
      copy:
        src: /home/ansible/securityenhancement.sh
        dest: /home/ansible/
        owner: ansible
        group: ansible
        mode: 0775
    - name: Execute the script
      shell: sh /home/ansible/securityenhancement.sh
